---
title: "Differential Privacy in Practice"
author: "Caleb Moses"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  rmarkdown::html_document:
    theme: lumen
---

# Introduction

This R notebook aims to provide a practical example of Differential Privacy for official statistics with microdata.

We will import a microdataset and perform some differentially private queries. Then we will assess the accuracy of the differential private estimates.

```{r message=FALSE, warning=TRUE}
# Import libraries
library(tidyverse)
library(kableExtra)
```

```{r}
raw_census <- read_csv('../data/rft-teaching-file/2011 Census Microdata Teaching File.csv', skip = 1)
```

```{r}
census <- raw_census %>% 
  mutate(
    Region = case_when(
      Region == 'E12000001' ~ 'North East',
      Region == 'E12000002' ~ 'North West',
      Region == 'E12000003' ~ 'Yorkshire and the Humber',
      Region == 'E12000004' ~ 'East Midlands',
      Region == 'E12000005' ~ 'West Midlands',
      Region == 'E12000006' ~ 'East of England',
      Region == 'E12000007' ~ 'London',
      Region == 'E12000008' ~ 'South East',
      Region == 'E12000009' ~ 'South West',
      Region == 'W92000004' ~ 'Wales',
      TRUE ~ warning("Not all Region values assigned")),
    `Residence Type` = case_when(
      `Residence Type` == 'C' ~ 'Resident in a communal establishment',
      `Residence Type` == 'H' ~ 'Not resident in a communal establishment'
      ),
    `Family Composition` = case_when(
      `Family Composition` == 1 ~ 'Not in a family',
      `Family Composition` == 2 ~ 'Married/same-sex civil partnership couple family',
      `Family Composition` == 3 ~ 'Cohabiting couple family',
      `Family Composition` == 4 ~ 'Lone parent family (male head)',
      `Family Composition` == 5 ~ 'Lone parent family (female head)',
      `Family Composition` == 6 ~ 'Other related family',
      `Family Composition` == -9 ~ 'No code required (Resident of a communal establishment, students or schoolchildren living away during term-time, or a short-term resident)'
      ),
    `Population Base` = case_when(
      `Population Base` == 1 ~ 'Usual resident',
      `Population Base` == 2 ~ 'Student living away from home during  term-time',
      `Population Base` == 3 ~ 'Short-term resident'
      ),
    Sex = case_when(
      Sex == 1 ~ 'Male',
      Sex == 2 ~ 'Female'
      ),
    Age = case_when(
      Age == 1 ~ '0 to 15',
      Age == 2 ~ '16 to 24',
      Age == 3 ~ '25 to 34',
      Age == 4 ~ '35 to 44',
      Age == 5 ~ '45 to 54',
      Age == 6 ~ '55 to 64',
      Age == 7 ~ '65 to 74',
      Age == 8 ~ '75 and over'
      ),
    `Marital Status` = case_when(
    `Marital Status` == 1 ~ 'Single (never married or never registered a same-sex civil partnership)',
    `Marital Status` == 2 ~ 'Married or in a registered same-sex civil partnership',
    `Marital Status` == 3 ~ 'Separated but still legally married or separated but still legally in a same-sex civil partnership',
    `Marital Status` == 4 ~ 'Divorced or formerly in a same-sex civil partnership which is now legally dissolved',
    `Marital Status` == 5 ~ 'Widowed or surviving partner from a same-sex civil partnership'
    ),
  Student = case_when(
    Student == 1 ~ 'Yes',
    Student == 2 ~ 'No'
    ),
  `Country Of Birth` = case_when(
    `Country of Birth` == 1 ~ 'UK',
    `Country of Birth` == 2 ~ 'Non UK',
    `Country of Birth` == -9 ~ 'No Code required (Students or schoolchildren living away during term-time)'
    ),
  Health = case_when(
    Health == 1 ~ 'Very good health',
    Health == 2 ~ 'Good health',
    Health == 3 ~ 'Fair health',
    Health == 4 ~ 'Bad health',
    Health == 5 ~ 'Very bad health',
    Health == -9 ~ 'No code required (Students or schoolchildren living away during term-time)'
    
    ),
  `Ethnic Group` = case_when(
    `Ethnic Group` == 1 ~ 'White',
    `Ethnic Group` == 2 ~ 'Mixed',
    `Ethnic Group` == 3 ~ 'Asian and Asian British',
    `Ethnic Group` == 4 ~ 'Black or Black British',
    `Ethnic Group` == 5 ~ 'Chinese or Other ethnic group',
    `Ethnic Group` == -9 ~ 'No code required (Not resident in England or Wales, students or schoolchildren living away during term-time)'
    
    ),
  Religion = case_when(
    Religion == 1 ~ 'No religion',
    Religion == 2 ~ 'Christian',
    Religion == 3 ~ 'Buddhist',
    Religion == 4 ~ 'Hindu',
    Religion == 5 ~ 'Jewish',
    Religion == 6 ~ 'Muslim',
    Religion == 7 ~ 'Sikh',
    Religion == 8 ~ 'Other religion',
    Religion == 9 ~ 'Not stated',
    Religion == -9 ~ 'No code required (Not resident in England or Wales, students or schoolchildren living away during term-time)'
    ),
  `Economic Activity` = case_when(
    `Economic Activity` == 1 ~ 'Economically active: Employee',
    `Economic Activity` == 2 ~ 'Economically active: Self-employed',
    `Economic Activity` == 3 ~ 'Economically active: Unemployed',
    `Economic Activity` == 4 ~ 'Economically active: Full-time student',
    `Economic Activity` == 5 ~ 'Economically inactive: Retired',
    `Economic Activity` == 6 ~ 'Economically inactive: Student',
    `Economic Activity` == 7 ~ 'Economically inactive: Looking after home or family',
    `Economic Activity` == 8 ~ 'Economically inactive: Long-term sick or disabled',
    `Economic Activity` == 9 ~ 'Economically inactive: Other',
    `Economic Activity` == -9 ~ 'No code required (Aged under 16 or students or schoolchildren living away during term-time)'
    ),
  Occupation = case_when(
    Occupation == 1 ~ 'Managers, Directors and Senior Officials',
    Occupation == 2 ~ 'Professional Occupations',
    Occupation == 3 ~ 'Associate Professional and Technical Occupations',
    Occupation == 4 ~ 'Administrative and Secretarial Occupations',
    Occupation == 5 ~ 'Skilled Trades Occupations',
    Occupation == 6 ~ 'Caring, Leisure and Other Service Occupations',
    Occupation == 7 ~ 'Sales and Customer Service Occupations',
    Occupation == 8 ~ 'Process, Plant and Machine Operatives',
    Occupation == 9 ~ 'Elementary Occupations',
    Occupation == -9 ~ 'No code required (People aged under 16, people who have never worked and students or schoolchildren living away during term-time)'
    ),
  Industry = case_when(
    Industry == 1 ~ 'Agriculture, forestry and fishing',
    Industry == 2 ~ 'Mining and quarrying; Manufacturing; Electricity, gas, steam and air conditioning system; Water supply',
    Industry == 3 ~ 'Construction',
    Industry == 4 ~ 'Wholesale and retail trade; Repair of motor vehicles and motorcycles',
    Industry == 5 ~ 'Accommodation and food service activities',
    Industry == 6 ~ 'Transport and storage; Information and communication',
    Industry == 7 ~ 'Financial and insurance activities; Intermediation',
    Industry == 8 ~ 'Real estate activities; Professional, scientific and technical activities; Administrative and support service activities',
    Industry == 9 ~ 'Public administration and defence; compulsory social security',
    Industry == 10 ~ 'Education',
    Industry == 11 ~ 'Human health and social work activities',
    Industry == 12 ~ 'Other community, social and personal service activities; Private households employing domestic staff; Extra-territorial organisations and bodies',
    Industry == -9 ~ 'No code required (People aged under 16, people who have never worked, and students or schoolchildren living away during term-time)'
    ),
  `Hours Worked Per Week` = case_when(
    `Hours worked per week` == 1 ~ 'Part-time: 15 or less hours worked',
    `Hours worked per week` == 2 ~ 'Part-time: 16 to 30 hours worked',
    `Hours worked per week` == 3 ~ 'Full-time: 31 to 48 hours worked',
    `Hours worked per week` == 4 ~ 'Full-time: 49 or more hours worked',
    `Hours worked per week` == -9 ~ 'No code required (People aged under 16, people not working, and students or schoolchildren living away during term-time)'
    ),
  `Approximated Social Grade` = case_when(
    `Approximated Social Grade` == 1 ~ 'AB',
    `Approximated Social Grade` == 2 ~ 'C1',
    `Approximated Social Grade` == 3 ~ 'C2',
    `Approximated Social Grade` == 4 ~ 'DE',
    `Approximated Social Grade` == -9 ~ 'No code required (People aged under 16, people resident in communal establishments, and students or schoolchildren living away during term-time)'
    ),
  ) %>% 
  select(-`Hours worked per week`, -`Country of Birth`)
```

```{r}
census_nas <- map_lgl(census, ~any(is.na(.)))
if (any(census_nas)) {
  print(census_nas)
  warning("Not all values assigned")
}
```

```{r}
census %>%
  sample_n(30) %>%
  knitr::kable() %>%
  kable_styling(font_size = 15) %>%
  scroll_box(width = "900px")
```

```{r}

```
































